<a href="https://colab.research.google.com/github/edgardbertelli/estudo-numpy/blob/main/NumPy_quickstart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy quickstart

## The basics

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.itemsize

8

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([6, 7, 8])

In [11]:
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

### Array creation

In [13]:
a = np.array([2, 3, 4])

In [14]:
a

array([2, 3, 4])

In [15]:
a.dtype

dtype('int64')

In [16]:
b = np.array([1.2, 3.5, 5.1])

In [17]:
b.dtype

dtype('float64')

In [18]:
a = np.array(1, 2, 3, 4)

TypeError: ignored

In [19]:
a = np.array([1, 2, 3, 4])

In [20]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [21]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [22]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

In [23]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [24]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [26]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [27]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [28]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [29]:
from numpy import pi

In [30]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
x = np.linspace(0, 2 * pi, 100)

In [32]:
f = np.sin(x)

### Printing arrays

In [33]:
a = np.arange(6)

In [34]:
print(a)

[0 1 2 3 4 5]


In [35]:
b = np.arange(12).reshape(4, 3)

In [36]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [37]:
c = np.arange(24).reshape(2, 3, 4)

In [38]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [39]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [40]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


### Basic operations

In [41]:
a = np.array([20, 30, 40, 50])

In [42]:
b = np.arange(4)

In [43]:
b

array([0, 1, 2, 3])

In [44]:
c = a - b

In [45]:
c

array([20, 29, 38, 47])

In [46]:
b**2

array([0, 1, 4, 9])

In [47]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [48]:
a < 35

array([ True,  True, False, False])

In [60]:
A = np.array([[1, 1],
              [0, 1]])

In [57]:
B = np.array([[2, 0],
              [3, 4]])

In [61]:
A * B

array([[2, 0],
       [0, 4]])

In [62]:
A @ B

array([[5, 4],
       [3, 4]])

In [63]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [64]:
rg = np.random.default_rng(1)

In [65]:
a = np.ones((2, 3), dtype=int)

In [66]:
b = rg.random((2, 3))

In [67]:
a *= 3

In [68]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [69]:
b += a

In [70]:
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [71]:
a += b

UFuncTypeError: ignored

In [72]:
a = np.ones(3, dtype=np.int32)

In [73]:
b = np.linspace(0, pi, 3)

In [74]:
b.dtype.name

'float64'

In [75]:
c = a + b

In [76]:
c

array([1.        , 2.57079633, 4.14159265])

In [77]:
c.dtype.name

'float64'

In [78]:
d = np.exp(c * 1j)

In [79]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [80]:
d.dtype.name

'complex128'

In [81]:
a = rg.random((2, 3))

In [82]:
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [83]:
a.sum()

3.1057109529998157

In [84]:
a.min()

0.027559113243068367

In [85]:
a.max()

0.8277025938204418

In [86]:
b = np.arange(12).reshape(3, 4)

In [87]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [89]:
b.min(axis=1)

array([0, 4, 8])

In [90]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### Universal functions

In [91]:
B = np.arange(3)

In [92]:
B

array([0, 1, 2])

In [93]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [94]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [95]:
C = np.array([2., -1., 4.])

In [96]:
np.add(B, C)

array([2., 0., 6.])

### Indexing, slicing and iterating

In [97]:
a = np.arange(10)**3

In [98]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [99]:
a[2]

8

In [100]:
a[2:5]

array([ 8, 27, 64])

In [101]:
a[:6:2] = 1000

In [102]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [103]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [104]:
for i in a:
    print(i**(1 / 3.))


9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [105]:
def f(x, y):
    return 10 * x + y


In [106]:
b = np.fromfunction(f, (5, 4), dtype=int)

In [107]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [108]:
b[2, 3]

23

In [109]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [110]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [111]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [112]:
b[-1]

array([40, 41, 42, 43])

In [113]:
c = np.array([[[0, 1, 2],
               [10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

In [114]:
c.shape

(2, 2, 3)

In [115]:
c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [116]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

In [117]:
for row in b:
    print(row)


[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [118]:
for element in b.flat:
    print(element)


0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
